on:
  workflow_dispatch:

jobs:
  actions-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4.2.2
        with: # input qui il attande
          name: ahmed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
