on:
  workflow_dispatch:

jobs:
  hybrid-job:
    runs-on: ubuntu-latest
    steps:
      - name: run a command in ubuntu vm
        run: echo "this runs on the ubuntu vm"
      - name: run inside an alpine conatiner 
        uses: docker://alpine:3.14
        with:
          entrypoint: /bin/sh
          args: |
            -c "echo 'this step runs inside an alpine conatiner'"
        
      - name: Run another command in ubuntu vm
        run: echo "back to the vm "


       
        
            
          
