on: 
    workflow_dispatch:
jobs:
    exemple:
        runs-on: ubuntu-latest
        steps:
            - name: set api key
              run: echo " API_KEY=1234" >> $GITHUB_ENV
            - name: user APi key
              run: echo "using APi key $API_KEY"
