on: 
  workflow_dispatch:

jobs:
  exemple:
    runs-on: ubuntu-latest
    steps:
      - name: Set API_KEY
        run: echo "API_KEY=1234" >> $GITHUB_ENV

      - name: Use API_KEY
        run: echo "using API key $API_KEY"
