on: 
  workflow_dispatch:

jobs:
  exemple:
    runs-on: ubuntu-latest
    steps:
      - name: ckeck if a file exists
        run: | 
          if [-f "config.yaml"]; then
            echo "::debug::config.yaml exists"
          else 
            echo "::error::config.yaml is missing"
          fi

      
